import { responseDefault } from '.';

export const postMembersMsg = {
  MEMBER_REGISTRATION_SUCCESS: 'MEMBER_REGISTRATION_SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  MEMBER_ALREADY_REGISTERED: 'MEMBER_ALREADY_REGISTERED',
} as const;

export const postMembersLoginMsg = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  BAD_REQUEST_BODY: 'BAD_REQUEST_BODY',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MEMBER_EMAIL_NOT_FOUND: 'MEMBER_EMAIL_NOT_FOUND',
} as const;

export const getMembersExistsByEmailMsg = {
  MEMBER_EMAIL_FIND_SUCCESS: 'MEMBER_EMAIL_FIND_SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export const postMembersAuthsMsg = {
  MEMBER_INVITE_SUCCESS: 'MEMBER_INVITE_SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_MEMBER_AUTHORIZATION: 'INVALID_MEMBER_AUTHORIZATION',
  INVALID_MEDIA_AUTHORIZATION: 'INVALID_MEDIA_AUTHORIZATION',
  MEMBER_EMAIL_NOT_FOUND: 'MEMBER_EMAIL_NOT_FOUND',
  MEMBER_ALREADY_INVITED: 'MEMBER_ALREADY_INVITED',
} as const;

export const patchMembersAuthsMsg = {
  MEMBER_JOIN_SUCCESS: 'MEMBER_JOIN_SUCCESS',
  BAD_REQUEST_UUID: 'BAD_REQUEST_UUID',
  MEMBER_INVITE_NOT_FOUND: 'MEMBER_INVITE_NOT_FOUND',
  MEMBER_ALREADY_JOINED: 'MEMBER_ALREADY_JOINED',
  ...responseDefault,
} as const;

export const deleteMembersAuthsMsg = {
  MEMBER_AUTH_DELETE_SUCCESS: 'MEMBER_AUTH_DELETE_SUCCESS',
  BAD_REQUEST_UUID: 'BAD_REQUEST_UUID',
  MEMBER_INVITE_NOT_FOUND: 'MEMBER_INVITE_NOT_FOUND',
  ...responseDefault,
} as const;

export const putMembersAuthsMsg = {
  MEMBER_AUTH_UPDATE_SUCCESS: 'MEMBER_AUTH_UPDATE_SUCCESS',
  INVALID_MEMBER_AUTHORIZATION: 'INVALID_MEMBER_AUTHORIZATION',
  INVALID_MEDIA_AUTHORIZATION: 'INVALID_MEDIA_AUTHORIZATION',
  ...responseDefault,
} as const;

export const getMembersAuthsMsg = {
  MEMBER_AUTH_LIST_GET_SUCCESS: 'MEMBER_AUTH_LIST_GET_SUCCESS',
  ...responseDefault,
} as const;

export const getMembersClientsMsg = {
  MEMBER_CLIENT_LIST_GET_SUCCESS: 'MEMBER_CLIENT_LIST_GET_SUCCESS',
  MISSING_REQUIRED_PARAMETER: 'MISSING_REQUIRED_PARAMETER',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  ...responseDefault,
} as const;

export const patchMembersClientsMsg = {
  CLIENT_ACCOUNT_SELECTED_SUCCESS: 'CLIENT_ACCOUNT_SELECTED_SUCCESS',
  MISSING_REQUIRED_PARAMETER: 'MISSING_REQUIRED_PARAMETER',
  INVALID_CLIENT_ACCOUNT: 'INVALID_CLIENT_ACCOUNT',
  ...responseDefault,
} as const;

export const getMembersAdMsg = {
  MEMBER_AD_STATUS_GET_SUCCESS: 'MEMBER_AD_STATUS_GET_SUCCESS',
  ...responseDefault,
} as const;

export const patchMembersAdMsg = {
  MEMBER_AD_UPDATE_SUCCESS: 'MEMBER_AD_UPDATE_SUCCESS',
  BAD_REQUEST_BODY: 'BAD_REQUEST_BODY',
  ...responseDefault,
} as const;

export const patchMembersPwMsg = {
  MEMBER_AD_UPDATE_SUCCESS: 'MEMBER_AD_UPDATE_SUCCESS',
  BAD_REQUEST_BODY: 'BAD_REQUEST_BODY',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MEMBER_EMAIL_NOT_FOUND: 'MEMBER_EMAIL_NOT_FOUND',
  SAME_PASSWORD: 'SAME_PASSWORD',
  ...responseDefault,
} as const;

export const postMembersVerifyEmailMsg = {
  VERIFY_EMAIL_SEND_SUCCESS: 'VERIFY_EMAIL_SEND_SUCCESS',
  MEMBER_EMAIL_NOT_FOUND: 'MEMBER_EMAIL_NOT_FOUND',
  EMAIL_SEND_FAIL: 'EMAIL_SEND_FAIL',
  ...responseDefault,
} as const;

export const patchMembersVerifyEmailMsg = {
  EMAIL_VERIFY_SUCCESS: 'EMAIL_VERIFY_SUCCESS',
  BAD_REQUEST_MISSING_PARAMETER: 'BAD_REQUEST_MISSING_PARAMETER',
  EMAIL_VERIFY_TOKEN_EXPIRED: 'EMAIL_VERIFY_TOKEN_EXPIRED',
  INVALID_EMAIL_VERIFY_TOKEN: 'INVALID_EMAIL_VERIFY_TOKEN',
  EMAIL_VERIFY_NOT_FOUND: 'EMAIL_VERIFY_NOT_FOUND',
  ...responseDefault,
} as const;

export const patchMembersPwByEmailMsg = {
  MEMBER_PW_BY_EMAIL_UPDATE_SUCCESS: 'MEMBER_PW_BY_EMAIL_UPDATE_SUCCESS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MEMBER_EMAIL_NOT_FOUND: 'MEMBER_EMAIL_NOT_FOUND',
  SAME_PASSWORD: 'SAME_PASSWORD',
  ...responseDefault,
} as const;

export const postMemberJoinEmailMsg = {
  JOIN_EMAIL_SEND_SUCCESS: 'JOIN_EMAIL_SEND_SUCCESS',
  EMAIL_SEND_FAIL: 'EMAIL_SEND_FAIL',
  ...responseDefault,
} as const;

export const postClientsAccountsMsg = {
  CLIENT_ACCOUNT_INSERT_SUCCESS: 'CLIENT_ACCOUNT_INSERT_SUCCESS',
  CLIENT_ID_ALREADY_EXIST: 'CLIENT_ID_ALREADY_EXIST',
  CLIENT_NAME_ALREADY_EXIST: 'CLIENT_NAME_ALREADY_EXIST',
  ...responseDefault
} as const;

export const putClientsAccountsMsg = {
  CLIENT_ACCOUNT_UPDATE_SUCCESS: 'CLIENT_ACCOUNT_UPDATE_SUCCESS',
  INVALID_MEMBER_AUTHORIZATION: 'INVALID_MEMBER_AUTHORIZATION',
  INVALID_CLIENT_ACCOUNT: 'INVALID_CLIENT_ACCOUNT',
  ...responseDefault
} as const;

export const patchClientsAccountsMsg = {
  CLIENT_ACCOUNT_STATUS_UPDATE_SUCCESS: 'CLIENT_ACCOUNT_STATUS_UPDATE_SUCCESS',
  ...responseDefault
} as const;

export const getClientsAccountsExistByIdMsg = {
  CLIENTSACCOUNTS_ID_FIND_SUCCESS: 'CLIENTSACCOUNTS_ID_FIND_SUCCESS',
  ...responseDefault
} as const;

export const getClientsAccountsExistByNameMsg = {
  CLIENTSACCOUNTS_NAME_FIND_SUCCESS: 'CLIENTSACCOUNTS_NAME_FIND_SUCCESS',
  ...responseDefault
} as const;

export const getClientsDefaultPageMsg = {
  DB_CLIENTS_DEFAULT_PAGE_GET_SUCCESS: 'DB_CLIENTS_DEFAULT_PAGE_GET_SUCCESS',
  BAD_REQUEST_UUID: 'BAD_REQUEST_UUID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ...responseDefault
} as const;

export const patchClientsDefaultPageMsg = {
  DB_FILTER_DEFAULT_PAGE_UPDATE_SUCCESS: 'DB_FILTER_DEFAULT_PAGE_UPDATE_SUCCESS',
  BAD_REQUEST_BODY: 'BAD_REQUEST_BODY',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  NOT_ALLOW_PAGE_STATUS_OFF: 'NOT_ALLOW_PAGE_STATUS_OFF',
  ...responseDefault
} as const;